# Generated by Django 5.2.6 on 2025-09-22 12:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "business_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(db_index=True, max_length=200)),
                (
                    "business_name_kinyarwanda",
                    models.CharField(blank=True, max_length=200),
                ),
                ("description", models.TextField()),
                ("description_kinyarwanda", models.TextField(blank=True)),
                ("province", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("cell", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("secondary_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("business_hours", models.JSONField(default=dict)),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("low", "Low ($)"),
                            ("medium", "Medium ($$)"),
                            ("high", "High ($$$)"),
                            ("premium", "Premium ($$$$)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("amenities", models.JSONField(default=list)),
                ("services_offered", models.JSONField(default=list)),
                ("payment_methods", models.JSONField(default=list)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="businesses/logos/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="businesses/covers/"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("search_keywords", models.JSONField(default=list)),
                ("meta_description", models.TextField(blank=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("contact_clicks", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "businesses",
            },
        ),
        migrations.CreateModel(
            name="BusinessAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("unique_viewers", models.PositiveIntegerField(default=0)),
                ("views_this_month", models.PositiveIntegerField(default=0)),
                ("views_this_week", models.PositiveIntegerField(default=0)),
                ("search_appearances", models.PositiveIntegerField(default=0)),
                ("search_clicks", models.PositiveIntegerField(default=0)),
                ("top_search_keywords", models.JSONField(default=list)),
                ("contact_clicks", models.PositiveIntegerField(default=0)),
                ("direction_requests", models.PositiveIntegerField(default=0)),
                ("website_clicks", models.PositiveIntegerField(default=0)),
                ("review_velocity", models.FloatField(default=0.0)),
                ("rating_trend", models.JSONField(default=list)),
                ("view_to_contact_rate", models.FloatField(default=0.0)),
                ("search_to_view_rate", models.FloatField(default=0.0)),
                ("peak_hours", models.JSONField(default=list)),
                ("peak_days", models.JSONField(default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "db_table": "business_analytics",
            },
        ),
        migrations.CreateModel(
            name="BusinessCategory",
            fields=[
                (
                    "category_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_kinyarwanda", models.CharField(blank=True, max_length=100)),
                ("name_french", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("description_kinyarwanda", models.TextField(blank=True)),
                ("description_french", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color_code", models.CharField(default="#6366f1", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="businesses.businesscategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Business Categories",
                "db_table": "business_categories",
            },
        ),
        migrations.AddField(
            model_name="business",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="businesses.businesscategory",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True,
                related_name="subcategory_businesses",
                to="businesses.businesscategory",
            ),
        ),
        migrations.CreateModel(
            name="BusinessClaim",
            fields=[
                (
                    "claim_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("proof_documents", models.JSONField(default=list)),
                (
                    "business_license",
                    models.ImageField(
                        blank=True, null=True, upload_to="claims/licenses/"
                    ),
                ),
                (
                    "identification",
                    models.ImageField(blank=True, null=True, upload_to="claims/ids/"),
                ),
                ("claim_reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="businesses.business",
                    ),
                ),
                (
                    "claimant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_claims",
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_special_day", models.BooleanField(default=False)),
                ("special_date", models.DateField(blank=True, null=True)),
                ("special_note", models.CharField(blank=True, max_length=200)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "db_table": "business_hours",
            },
        ),
        migrations.CreateModel(
            name="BusinessImage",
            fields=[
                (
                    "image_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="businesses/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "db_table": "business_images",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "review_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField(blank=True)),
                (
                    "service_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "quality_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "value_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("helpful_votes", models.PositiveIntegerField(default=0)),
                ("reported_count", models.PositiveIntegerField(default=0)),
                ("business_response", models.TextField(blank=True)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="businesses.business",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["business_name"], name="businesses_busines_ab9e68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["category"], name="businesses_categor_59d3ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["province", "district"], name="businesses_provinc_1df842_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["verification_status"], name="businesses_verific_e87a86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["is_active"], name="businesses_is_acti_8eca54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["latitude", "longitude"], name="businesses_latitud_a1cf4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["created_at"], name="businesses_created_bb3563_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="businesshours",
            unique_together={("business", "day_of_week", "special_date")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["business", "rating_score"], name="reviews_busines_19b0a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["created_at"], name="reviews_created_53b5d6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("business", "reviewer")},
        ),
    ]
