# Generated by Django 5.2.6 on 2025-09-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="location_accuracy",
            field=models.FloatField(
                blank=True, help_text="GPS accuracy in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="location_detected_at",
            field=models.DateTimeField(
                blank=True, help_text="When location was last detected", null=True
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="profile_completion_percentage",
            field=models.IntegerField(
                default=0, help_text="Profile completion percentage"
            ),
        ),
    ]
