# Generated by Django 5.2.6 on 2025-09-22 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_term", models.CharField(max_length=200, unique=True)),
                ("search_count", models.PositiveIntegerField(default=1)),
                ("language", models.CharField(default="en", max_length=10)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("searches_this_week", models.PositiveIntegerField(default=0)),
                ("searches_this_month", models.PositiveIntegerField(default=0)),
                ("trend_score", models.FloatField(default=0.0)),
                ("last_searched", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "popular_searches",
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "query_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField()),
                ("original_language", models.CharField(default="en", max_length=10)),
                ("processed_query", models.TextField(blank=True)),
                ("user_location", models.JSONField(blank=True, null=True)),
                ("search_filters", models.JSONField(default=dict)),
                ("search_type", models.CharField(default="general", max_length=50)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("clicked_business_ids", models.JSONField(default=list)),
                ("user_satisfaction", models.IntegerField(blank=True, null=True)),
                ("response_time_ms", models.PositiveIntegerField(null=True)),
                ("search_session_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_queries",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="search_quer_user_id_175990_idx",
                    ),
                    models.Index(
                        fields=["query_text"], name="search_quer_query_t_f8c040_idx"
                    ),
                    models.Index(
                        fields=["search_type"], name="search_quer_search__d20f8f_idx"
                    ),
                ],
            },
        ),
    ]
