# Generated by Django 5.2.6 on 2025-09-22 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RwandaProvince",
            fields=[
                (
                    "province_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_kinyarwanda", models.CharField(max_length=100)),
                ("name_french", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("area_km2", models.FloatField()),
                ("population", models.IntegerField(blank=True, null=True)),
                ("boundaries", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rwanda_provinces",
            },
        ),
        migrations.CreateModel(
            name="RwandaDistrict",
            fields=[
                (
                    "district_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_kinyarwanda", models.CharField(max_length=100)),
                ("name_french", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("area_km2", models.FloatField()),
                ("population", models.IntegerField(blank=True, null=True)),
                ("boundaries", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="locations.rwandaprovince",
                    ),
                ),
            ],
            options={
                "db_table": "rwanda_districts",
                "unique_together": {("province", "name")},
            },
        ),
        migrations.CreateModel(
            name="RwandaSector",
            fields=[
                (
                    "sector_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_kinyarwanda", models.CharField(max_length=100)),
                ("name_french", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="locations.rwandadistrict",
                    ),
                ),
            ],
            options={
                "db_table": "rwanda_sectors",
                "unique_together": {("district", "name")},
            },
        ),
        migrations.CreateModel(
            name="RwandaCell",
            fields=[
                (
                    "cell_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_kinyarwanda", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="locations.rwandasector",
                    ),
                ),
            ],
            options={
                "db_table": "rwanda_cells",
                "unique_together": {("sector", "name")},
            },
        ),
    ]
