# Generated by Django 5.2.6 on 2025-09-22 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle_type_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("car", "Car"),
                            ("van", "Van"),
                            ("bus", "Bus"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "base_fare",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "per_minute_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "minimum_fare",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Vehicle Type",
                "verbose_name_plural": "Vehicle Types",
                "db_table": "vehicle_types",
            },
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ride_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pickup_latitude",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(decimal_places=8, max_digits=11),
                ),
                ("pickup_address", models.TextField()),
                (
                    "dropoff_latitude",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "dropoff_longitude",
                    models.DecimalField(decimal_places=8, max_digits=11),
                ),
                ("dropoff_address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_fare",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_fare",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="RWF", max_length=3)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("passenger_count", models.PositiveIntegerField(default=1)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_as_passenger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides",
                        to="transportation.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride",
                "verbose_name_plural": "Rides",
                "db_table": "rides",
            },
        ),
        migrations.CreateModel(
            name="RideReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "driver_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "vehicle_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("review_text", models.TextField(blank=True)),
                ("was_on_time", models.BooleanField(default=True)),
                ("was_polite", models.BooleanField(default=True)),
                ("vehicle_clean", models.BooleanField(default=True)),
                ("safe_driving", models.BooleanField(default=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="transportation.ride",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride Review",
                "verbose_name_plural": "Ride Reviews",
                "db_table": "ride_reviews",
            },
        ),
        migrations.CreateModel(
            name="FareCalculation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pickup_latitude",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(decimal_places=8, max_digits=11),
                ),
                (
                    "dropoff_latitude",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "dropoff_longitude",
                    models.DecimalField(decimal_places=8, max_digits=11),
                ),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("distance_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="RWF", max_length=3)),
                (
                    "calculation_method",
                    models.CharField(default="standard", max_length=50),
                ),
                (
                    "surge_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fare_calculations",
                        to="transportation.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fare Calculation",
                "verbose_name_plural": "Fare Calculations",
                "db_table": "fare_calculations",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("license_expiry", models.DateField()),
                ("vehicle_model", models.CharField(max_length=100)),
                ("vehicle_plate", models.CharField(max_length=20)),
                ("vehicle_color", models.CharField(max_length=50)),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("location_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_rides", models.PositiveIntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "license_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="drivers/licenses/"
                    ),
                ),
                (
                    "vehicle_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="drivers/vehicles/"
                    ),
                ),
                (
                    "insurance_document",
                    models.ImageField(
                        blank=True, null=True, upload_to="drivers/insurance/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drivers",
                        to="transportation.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "db_table": "drivers",
            },
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["passenger", "status"], name="rides_passeng_fda548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["driver", "status"], name="rides_driver__d736b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["status", "requested_at"], name="rides_status_243aa6_idx"
            ),
        ),
    ]
