# Generated by Django 5.2.6 on 2025-09-22 13:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(default=True)),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_login_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="emailverification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="passwordreset",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="phoneverification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="emailverification",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="max_attempts",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="push_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sms_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_resets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="phoneverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                help_text="Rwanda phone number format: +250XXXXXXXXX",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in format: '+250XXXXXXXXX'",
                        regex="^\\+250[7][0-9]{8}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email_verified", "phone_verified"],
                name="users_email_v_56af83_idx",
            ),
        ),
        migrations.AddField(
            model_name="userloginlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userloginlog",
            index=models.Index(
                fields=["user", "created_at"], name="user_login__user_id_23713a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginlog",
            index=models.Index(
                fields=["ip_address"], name="user_login__ip_addr_c87602_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginlog",
            index=models.Index(
                fields=["success"], name="user_login__success_0bdb65_idx"
            ),
        ),
    ]
