# Generated by Django 5.2.6 on 2025-09-23 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "authentication",
            "0002_userloginlog_alter_emailverification_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailverification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
            },
        ),
        migrations.AlterModelOptions(
            name="passwordreset",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Password Reset",
                "verbose_name_plural": "Password Resets",
            },
        ),
        migrations.AlterModelOptions(
            name="phoneverification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Phone Verification",
                "verbose_name_plural": "Phone Verifications",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="userloginlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Login Log",
                "verbose_name_plural": "User Login Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Rwanda phone number format: +2507XXXXXXXX, 2507XXXXXXXX, or 07XXXXXXXX",
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be a valid Rwanda format: +2507XXXXXXXX, 2507XXXXXXXX, or 07XXXXXXXX",
                        regex="^(\\+250|250|0)[7][0-9]{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("business_owner", "Business Owner"),
                    ("admin", "Administrator"),
                    ("staff", "Staff"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userloginlog",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invalid_credentials", "Invalid Credentials"),
                    ("account_locked", "Account Locked"),
                    ("unverified_account", "Unverified Account"),
                    ("inactive_account", "Inactive Account"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_staff", "is_superuser"], name="users_is_staf_39dd61_idx"
            ),
        ),
    ]
